# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChessIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Auth'
  pod 'FirebaseUI'
  pod 'Firebase/Database'

  target 'ChessIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
